images_dir: /home/sashank/data/blade-load-segmentation/0915/3left/rgb
outputs_dir: /home/sashank/data/blade-load-segmentation/0915/3left/outputs
model:
  n_channels: 3
  n_classes: 2
  bilinear: False
  path: /workspace/data/work/models/runs/earthy-vortex-9/checkpoint_epoch3.pth
  input_size: 256