images_dir: /home/sashank/data/blade-load-segmentation/0915/3left/rgb
outputs_dir: /home/sashank/data/blade-load-segmentation/0915/3left/outputs
model:
  n_channels: 3
  n_classes: 2
  bilinear: False
  path: /home/sashank/data/blade-load-segmentation/d5-luyuan/checkpoints/checkpoint_epoch100.pth
  input_size: 256